workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'

image: 639869022467.dkr.ecr.eu-west-1.amazonaws.com/netcraft/docker/gitlab-executor:8

include:
  - project: netcraft/development/ci-templates
    ref: master
    file: build-k8s.yaml

stages:
  - deploy

ctr:prod:keda:
   stage: deploy
   when: manual
   variables:
     REPO: harbor.netcraft.com/netcraft/kedacore/keda
     EXTRA_BUILDKIT_ARGS: --opt platform=linux/amd64,linux/arm64
     DOCKER_FILE: Dockerfile
   extends:
     - .build_container
   rules:
     - changes:
         - "**/*.go"

ctr:prod:keda-metrics-apiserver:
   stage: deploy
   when: manual
   variables:
     REPO: harbor.netcraft.com/netcraft/kedacore/keda-metrics-apiserver
     EXTRA_BUILDKIT_ARGS: --opt platform=linux/amd64,linux/arm64
     DOCKER_FILE: Dockerfile.adapter
   extends:
     - .build_container
   rules:
     - changes:
         - "**/*.go"

ctr:prod:keda-admission-webhooks:
   stage: deploy
   when: manual
   variables:
     REPO: harbor.netcraft.com/netcraft/kedacore/keda-admission-webhooks
     EXTRA_BUILDKIT_ARGS: --opt platform=linux/amd64,linux/arm64
     DOCKER_FILE: Dockerfile.webhooks
   extends:
     - .build_container
   rules:
     - changes:
         - "**/*.go"