workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'

image: 639869022467.dkr.ecr.eu-west-1.amazonaws.com/netcraft/docker/gitlab-executor:8

include:
  - project: netcraft/development/ci-templates
    ref: master
    file: build-k8s.yaml
  - project: netcraft/development/ci-templates
    file: go.yaml

stages:
  - lint
  - build
  - test

lint:go:
  extends: .go_lint
  needs: []
  tags:
    - spot
  rules:
    - changes:
        - "./**/*.go"
      when: always
  stage: lint
  artifacts:
    when: always
    paths:
      - api/linter_output.xml
    reports:
      junit: api/linter_output.xml

ctr:test:keda:
  stage: build
  needs:
    - lint:go
  rules:
    - changes:
        - "./**/*.go"
      when: always
  variables:
    CI_IMAGE_SUFFIX: keda-dev
    EXTRA_BUILDKIT_ARGS: --opt platform=linux/amd64,linux/arm64
    DOCKER_FILE: Dockerfile
  extends:
    - .build_container

test:keda:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/keda:${CI_COMMIT_SHORT_SHA}
  extends: .go_test_with_coverage
  needs:
    - ctr:test:keda
  rules:
    - changes:
        - "./**/*.go"
      when: always